/*
 * Copyright 2025 patryk3211, 'Rory W. J. Smithee'
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *	 http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.patryk3211.powergrid.config;

import net.createmod.catnip.config.ConfigBase;

public class CGenerator extends ConfigBase {
	/* Gud Nuff values for the Kp and Kd terms. Tune these to your liking. */
	public final ConfigFloat rotorKp = f(0.85f, 0f, "rotorKp", Comments.rotorKp);
	public final ConfigFloat rotorKd = f(0.002f, 0f, "rotorKd", Comments.rotorKd);

	public final ConfigInt rotorRPMMax = i(256, 0, "rotorRPMMax", Comments.rotorRPMMax);

	public final ConfigInt rotorAssemblyMaxSize = i(8, 3, "rotorAssemblyMaxSize", Comments.rotorAssemblyMaxSize);
	public final ConfigFloat rotorSegmentFriction = f(0.25f, 0, "rotorSegmentFriction", Comments.rotorSegmentFriction);

	public final ConfigFloat generatorRotorInertia = f(0.15f, 0, "generatorRotorInertia");
	public final ConfigFloat generatorInductionRotorInertia = f(0.15f, 0, "generatorInductionRotorInertia");
	public final ConfigFloat generatorCommutatorInertia = f(0.05f, 0, "generatorCommutatorInertia");
	public final ConfigFloat generatorClutchInertia = f(0.05f, 0, "generatorClutchInertia");

	public final ConfigFloat windingCoilConstant = f(5, 0.1f, "windingCoilConstant", Comments.windingCoilConstant);
	public final ConfigFloat fieldSaturationCurrent = f(3.0f, 0, "fieldSaturationCurrent", Comments.fieldSaturationCurrent);

    @Override
    public String getName() {
        return "generatorControl";
    }

	private static class Comments {
		/* bla bla bla bla bla they do the thing. */
		public static final String rotorKp = "Factor to scale the Proportional factorof the Rotor's force calculation";
		public static final String rotorKd = "Factor to scale the Differential factor of the Rotor's force calculation";
		public static final String rotorRPMMax = "Maximum rotation speed of a rotor";
		public static final String rotorAssemblyMaxSize = "Maximum length of a rotor assembly";
		public static final String rotorSegmentFriction = "Force of friction applied for each segment of the rotor assembly";
		public static final String windingCoilConstant = "Controls the conversion rate between RPM and voltage generated by windings";
		public static final String fieldSaturationCurrent = "Current required for maximum field strength of the generator's field windings";
	}
}
