modLoader = "javafml"
loaderVersion = "[@FORGE_LOADER_MAJOR@,)"
issueTrackerURL = "https://github.com/patryk3211/PowerGrid/issues"
license = "Apache-2.0"

[[mods]]
modId = "powergrid"
version = "${version}"
displayName = "Create: Power Grid"
authors = "patryk3211, Da-Negy, rvndm"
description = '''
Providing electricity to a world near you.
'''
logoFile = "assets/powergrid/icon.png"

[[dependencies.powergrid]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.powergrid]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

#[[dependencies.powergrid]]
#modId = "architectury"
#mandatory = true
#versionRange = "[@ARCHITECTURY_API@,)"
#ordering = "AFTER"
#side = "BOTH"

[[dependencies.powergrid]]
modId = "create"
mandatory = true
versionRange = "[${create_forge_version},)"
ordering = "NONE"
side = "BOTH"
