plugins {
	id 'maven-publish'
	id 'architectury-plugin' version '3.4-SNAPSHOT'
	id 'dev.architectury.loom' version '1.9+' apply false
	id "com.github.johnrengelman.shadow" version "7.1.2"
}

architectury {
	minecraft = minecraft_version
}

var logConfig = file('log4j-dev.xml')
allprojects {
	apply plugin: "java"
	apply plugin: "architectury-plugin"
	apply plugin: "dev.architectury.loom"

	base.archivesName.set(project.archives_base_name)
	group = project.maven_group
	version = "${project.mod_version}-mc${project.minecraft_version}"

	tasks.withType(JavaCompile).configureEach {
		it.options.release = 17
	}

	repositories {
		maven { url = "https://maven.parchmentmc.org" } // Parchment mappings

		maven { url = "https://mvn.devos.one/releases" } // Porting Lib releases
		maven { url = "https://mvn.devos.one/snapshots" } // Create and several dependencies
		maven { url = "https://modmaven.dev/" } // Flywheel
		maven { url = "https://maven.jamieswhiteshirt.com/libs-release" } // Reach Entity Attributes
		maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven" } // Forge Config API Port
//		maven { url = "https://maven.ithundxr.dev/snapshots" } // Registrate
		maven { url = "https://maven.tterrag.com/" } // Registrate

		maven {
			url = "https://maven.createmod.net"
			content {
				includeGroupAndSubgroups("net.createmod")
				includeGroupAndSubgroups("dev.engine-room")
				includeGroupAndSubgroups("com.simibubi")
			}
		} // Flywheel, Registrate, Create

		maven { // Fabric ASM for Porting Lib
			url = "https://jitpack.io/"
			content { includeGroupAndSubgroups("com.github") }
		}

		maven { url = "https://maven.shedaniel.me" } // Cloth Config, REI
		maven { url = "https://maven.blamejared.com" } // JEI

		maven { url = "https://maven.terraformersmc.com/releases" } // Mod Menu, EMI
		maven { url = "$rootDir/local-maven" } // Create Fabric v6
	}

	loom {
//		mods {
//			"powergrid" {
//				sourceSet sourceSets.main
//	//			sourceSet sourceSets.client
//			}
//		}
//		remapArchives = true

		log4jConfigs.from(logConfig)
	}

	configurations {
		common
		shadowCommon
	}

	dependencies {
		minecraft "com.mojang:minecraft:${project.minecraft_version}"

		mappings(loom.layered {
			it.officialMojangMappings { nameSyntheticMembers = false }
			it.parchment("org.parchmentmc.data:parchment-${project.minecraft_version}:$parchment_version@zip")
		})

		implementation(include("org.ejml:ejml-core:0.44.0"))
		implementation(include("org.ejml:ejml-simple:0.44.0"))
		implementation(include("org.ejml:ejml-ddense:0.44.0"))
//		mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	}

	java {
		withSourcesJar()

		sourceCompatibility = JavaVersion.VERSION_17
		targetCompatibility = JavaVersion.VERSION_17
	}
}

def getGitHash = { ->
	def stdout = new ByteArrayOutputStream()
	exec {
		commandLine 'git', 'rev-parse', '--short', 'HEAD'
		standardOutput = stdout
	}
	return stdout.toString().trim()
}

subprojects {
	apply plugin: "com.github.johnrengelman.shadow"

	configurations.configureEach {
		resolutionStrategy {
			// Make sure the desired version of loader is used. Sometimes old versions are pulled in transitively.
			force("net.fabricmc:fabric-loader:${project.loader_version}")
		}
	}

	architectury {
		platformSetupLoomIde()
	}

	tasks.processResources {
		var properties = [
				version              : project.version,
				architectury_version : project.architectury_api_version,
				create_forge_version : project.create_forge_range,
				create_fabric_version: project.create_fabric_version,
				forge_version        : project.forge_version,
				fabric_version       : project.fabric_version,
				loader_version       : project.loader_version,
				minecraft_version    : project.minecraft_version
		]

		inputs.properties(properties)

		filesMatching(["fabric.mod.json", "META-INF/mods.toml"]) {
			expand(properties)
		}
	}

	configurations {
		compileClasspath.extendsFrom common
		runtimeClasspath.extendsFrom common
	}

	dependencies {
		common(project(path: rootProject.path, configuration: "namedElements")) { transitive false }
	}

	tasks.register("devBuild", {
		version = "${project.mod_version}+${project.minecraft_version}-${getGitHash}"
		dependsOn tasks.build
	})

	tasks.jar {
		inputs.property "archivesName", project.base.archivesName

		from("LICENSE") {
			rename { "${it}_${inputs.properties.archivesName}" }
		}

		from("NOTICE") {
			rename { "${it}_${inputs.properties.archivesName}" }
		}

		archiveClassifier = "dev"
	}

	tasks.named("remapJar") {
		inputFile.set shadowJar.archiveFile
		dependsOn shadowJar
		archiveClassifier = null
	}

	tasks.named("shadowJar") {
		configurations = [ project.configurations.shadowCommon ]
		archiveClassifier = "dev-shadow"
	}

	tasks.named("sourcesJar") {
		def commonSources = rootProject.sourcesJar
		dependsOn commonSources
		from commonSources.archiveFile.map { zipTree(it) }
	}

	components.named("java") {
		withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
			skip()
		}
	}
}

//fabricApi {
//	configureDataGeneration {
//		client = true
//	}
//}

// configure the maven publication
//publishing {
//	publications {
//		create("mavenJava", MavenPublication) {
//			artifactId = project.archives_base_name
//			from components.java
//		}
//	}
//
//	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
//	repositories {
//		// Add repositories to publish to here.
//		// Notice: This block does NOT have the same function as the block in the top level.
//		// The repositories here will be used for publishing your artifact, not for
//		// retrieving dependencies.
//	}
//}

/*    -------========= COMMON PROJECT CONFIGURATION =========-------    */

architectury {
	common(project.enabled_platforms.split(','))
}

dependencies {
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modCompileOnly("com.simibubi.create:create-fabric-${project.minecraft_version}:${project.create_fabric_version}")
	modCompileOnly("net.fabricmc.fabric-api:fabric-api:${fabric_version}")

	// Roughly Enough Items - Common
	modCompileOnly "me.shedaniel:RoughlyEnoughItems-api:${rei_version}"
//	modCompileOnly "me.shedaniel:RoughlyEnoughItems-default-plugin:${rei_version}"

//	modImplementation("com.simibubi.create:create-${minecraft_version}:${create_forge_version}:slim") { transitive false }
//	modImplementation("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_forge_version}") { transitive false }
//	modCompileOnly("dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_forge_version}") { transitive false }
//	modRuntimeOnly("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_forge_version}") { transitive false }
//	modImplementation("com.tterrag.registrate:Registrate:${registrate_forge_version}") { transitive false }

	// Support for unit tests
//	testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"

	modApi "dev.architectury:architectury:${project.architectury_api_version}"

	annotationProcessor(implementation("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
}

//test {
//	useJUnitPlatform()
//}

sourceSets.main {
	resources {
//		srcDir('src/main/generated')
		exclude(".cache/**")
		exclude("assets/create/**")
	}
}